config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback', to: 'sessions#create'

  root 'site/videos#index'

  scope module: :api do

    namespace :v0 do
      resources :help
    end

    namespace :v1 do
      resources :waves do
        collection do
          get 'updates_stream'
          post 'insert'
          post 'graph_points'
        end
      end

      resources :video_sessions do
        collection do
          post 'insert'
          post 'delete_all'
          post 'graph_points'
          delete 'master_delete_all'
        end
      end

      resources :videos do
        collection do
          post 'insert'
          post 'delete'
        end
      end

      resources :wave_logs, path: :wavelogs do
        collection do
          get 'all'
          post 'insert'
          post 'waves'
        end
      end

    end

  end

  scope module: :site do

    resources :waves do
      collection do
        get 'graph'
        get 'fake_headset'
      end
    end

    resources :videos do
      collection do
        get 'watch'
      end
    end

  end

  resources :users

  get 'signup' => 'users#new'
  get 'login'  => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "EEGHEAD", root_path %></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <% if current_user && current_user.professor? %>
    <ul class="left">
      <li><%= link_to "Add New Video", new_video_path %> </li>
    </ul>
    <% end %>
    <!-- Right Nav Section -->
    <ul class="right">
      <li><%= link_to "Videos", videos_path %> </li>
      <% if logged_in? %>
      <li><%= link_to "Profile", edit_user_path(current_user) %></a></li>
      <li class="has-dropdown"><a href="#">Account</a>
        <ul class="dropdown">
          <li><label><%= current_user.name %></label></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "Graphs", graph_waves_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Logout", logout_path, method: "delete" %></a></li>
          <li class="divider"></li>
        </ul>
      </li>
      <% else %>
        <li><%= link_to "Log in", login_path %>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>EEG HEAD</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <div data-alert class="alert-box <%= key %>">
        <%= value %>
        <a href='#' class="close">&times;</a>
      </div>
    <% end %>
    <%= yield %>
    <script>
      $(document).foundation();
    </script>
  </body>
</html>